project:
  type: website

title: Modelos de Grafos Exponenciales Aleatorios
subtitle: "***Una herramienta para investigadores aplicados***"
author: 
  - name: Juan C. Correa
orcid: 0000-0002-0301-5641
corresponding: TRUE
affiliation: Critical Centrality Institute 
url: 'https://correajc.com/'
email: jcc@criticalcentrality.com
date: "Julio 11 2024"
lang: es
bibliography: refs.bib
number-sections: true

website:
  title: ""
sidebar:
  left:
  - href: index.qmd
text: Home
- about.qmd

format:
  html:
  theme: cosmo
css: styles.css
toc: true

editor: visual

