load("Results/Result1.RData")
library(quanteda)
s1 <- data.frame(kwic(Programs, pattern = phrase("pensamiento crítico")))
s2 <- data.frame(kwic(Programs, pattern = phrase("solución de problemas")))
s3 <- data.frame(kwic(Programs, pattern = "comunica*"))
s4 <- data.frame(kwic(Programs, pattern = "crea*"))
s5 <- data.frame(kwic(Programs, pattern = "paciencia"))
s6 <- data.frame(kwic(Programs, pattern = "lider*"))
s7 <- data.frame(kwic(Programs, pattern = "resolv*"))
s8 <- data.frame(kwic(Programs, pattern = "comprom*"))
s9 <- data.frame(kwic(Programs, pattern = "emprende*"))
s10 <- data.frame(kwic(Programs, pattern = "gesti*"))
s11 <- data.frame(kwic(Programs, pattern = "reflexionar"))
s12 <- data.frame(kwic(Programs, pattern = "control*"))
s13 <- data.frame(kwic(Programs, pattern = "étic*"))
s14 <- data.frame(kwic(Programs, pattern = "tolera*"))
s15 <- data.frame(kwic(Programs, pattern = "argument*"))
s16 <- data.frame(kwic(Programs, pattern = "conflict*"))
s17 <- data.frame(kwic(Programs, pattern = "negocia*"))
s18 <- data.frame(kwic(Programs, pattern = "entender"))
s19 <- data.frame(kwic(Programs, pattern = phrase("trabajo en equipo")))
s20 <- data.frame(kwic(Programs, pattern = "planifi*"))
s21 <- data.frame(kwic(Programs, pattern = "genera*"))
s22 <- data.frame(kwic(Programs, pattern = "empatía"))
s23 <- data.frame(kwic(Programs, pattern = "compartir"))
s24 <- data.frame(kwic(Programs, pattern = "anali*"))
s25 <- data.frame(kwic(Programs, pattern = "reconoc*"))
s26 <- data.frame(kwic(Programs, pattern = "guiar"))
s27 <- data.frame(kwic(Programs, pattern = "respetar"))
s28 <- data.frame(kwic(Programs, pattern = "motiva*"))
s29 <- data.frame(kwic(Programs, pattern = "coopera*"))
s30 <- data.frame(kwic(Programs, pattern = "fortalecer"))
s31 <- data.frame(kwic(Programs, pattern = "empuj*"))
s32 <- data.frame(kwic(Programs, pattern = phrase("acercar")))
s33 <- data.frame(kwic(Programs, pattern = "conectar"))
s34 <- data.frame(kwic(Programs, pattern = "cambiar"))
s35 <- data.frame(kwic(Programs, pattern = "apreciar"))
s36 <- data.frame(kwic(Programs, pattern = "fomentar"))
s37 <- data.frame(kwic(Programs, pattern = "interactuar"))
s38 <- data.frame(kwic(Programs, pattern = "identificar"))
s39 <- data.frame(kwic(Programs, pattern = "competir"))
s40 <- data.frame(kwic(Programs, pattern = "manifestar"))
s41 <- data.frame(kwic(Programs, pattern = "responsable"))
s42 <- data.frame(kwic(Programs, pattern = "evalua*"))
s43 <- data.frame(kwic(Programs, pattern = "innova*"))
s44 <- data.frame(kwic(Programs, pattern = "deci*"))
s45 <- data.frame(kwic(Programs, pattern = "flexibilidad"))
s46 <- data.frame(kwic(Programs, pattern = "persua*"))
s47 <- data.frame(kwic(Programs, pattern = "convenc*"))
s48 <- data.frame(kwic(Programs, pattern = "inspir*"))
s49 <- data.frame(kwic(Programs, pattern = "estrat*"))
s50 <- data.frame(kwic(Programs, pattern = "recre*"))

df_list <- mget(paste0("s", 1:50))
SS <- do.call(rbind, df_list)
rm(list=setdiff(ls(), "SS"))
save.image("Results/Result2.RData")

