load("Results/Result1.RData")
library(quanteda)
s1 <- data.frame(kwic(Programs, pattern = phrase("critical thinking")))
s2 <- data.frame(kwic(Programs, pattern = phrase("problem solving")))
s3 <- data.frame(kwic(Programs, pattern = "communicat*"))
s4 <- data.frame(kwic(Programs, pattern = "creati*"))
s5 <- data.frame(kwic(Programs, pattern = "help*"))
s6 <- data.frame(kwic(Programs, pattern = "lead*"))
s7 <- data.frame(kwic(Programs, pattern = "solv*"))
s8 <- data.frame(kwic(Programs, pattern = "commitment"))
s9 <- data.frame(kwic(Programs, pattern = "entreprene*"))
s10 <- data.frame(kwic(Programs, pattern = "manag*"))
s11 <- data.frame(kwic(Programs, pattern = "reflect"))
s12 <- data.frame(kwic(Programs, pattern = "control*"))
s13 <- data.frame(kwic(Programs, pattern = "ethic*"))
s14 <- data.frame(kwic(Programs, pattern = "tolera*"))
s15 <- data.frame(kwic(Programs, pattern = "argu*"))
s16 <- data.frame(kwic(Programs, pattern = "conflict*"))
s17 <- data.frame(kwic(Programs, pattern = "negotia*"))
s18 <- data.frame(kwic(Programs, pattern = "understand*"))
s19 <- data.frame(kwic(Programs, pattern = "sales"))
s20 <- data.frame(kwic(Programs, pattern = "teamwork"))
s21 <- data.frame(kwic(Programs, pattern = "generat*"))
s22 <- data.frame(kwic(Programs, pattern = "empathy"))
s23 <- data.frame(kwic(Programs, pattern = "shar*"))
s24 <- data.frame(kwic(Programs, pattern = "analy*"))
s25 <- data.frame(kwic(Programs, pattern = "recogni*"))
s26 <- data.frame(kwic(Programs, pattern = "guid*"))
s27 <- data.frame(kwic(Programs, pattern = "respect*"))
s28 <- data.frame(kwic(Programs, pattern = "motiva*"))
s29 <- data.frame(kwic(Programs, pattern = "coopera*"))
s30 <- data.frame(kwic(Programs, pattern = "strength*"))
s31 <- data.frame(kwic(Programs, pattern = "push*"))
s32 <- data.frame(kwic(Programs, pattern = "challeng*"))
s33 <- data.frame(kwic(Programs, pattern = "conect*"))
s34 <- data.frame(kwic(Programs, pattern = "change"))
s35 <- data.frame(kwic(Programs, pattern = "appreciat*"))
s36 <- data.frame(kwic(Programs, pattern = "predict*"))
s37 <- data.frame(kwic(Programs, pattern = "interact*"))
s38 <- data.frame(kwic(Programs, pattern = "identif*"))
s39 <- data.frame(kwic(Programs, pattern = "compet*"))
s40 <- data.frame(kwic(Programs, pattern = "win*"))
s41 <- data.frame(kwic(Programs, pattern = "responsible"))
s42 <- data.frame(kwic(Programs, pattern = "evalua*"))
s43 <- data.frame(kwic(Programs, pattern = "innova*"))
s44 <- data.frame(kwic(Programs, pattern = "deci*"))
s45 <- data.frame(kwic(Programs, pattern = "flexibili*"))
s46 <- data.frame(kwic(Programs, pattern = "persua*"))
s47 <- data.frame(kwic(Programs, pattern = "convinc*"))
s48 <- data.frame(kwic(Programs, pattern = "inspir*"))
s49 <- data.frame(kwic(Programs, pattern = "strat*"))
s50 <- data.frame(kwic(Programs, pattern = "advertis*"))



df_list <- mget(paste0("s", 1:50))
SS <- do.call(rbind, df_list)
rm(list=setdiff(ls(), "SS"))
save.image("Results/Result2.RData")

