load("Results/Result1.RData")
library(quanteda)
s1 <- data.frame(kwic(Programs, pattern = phrase("critical thinking")))
s2 <- data.frame(kwic(Programs, pattern = phrase("problem solving")))
s3 <- data.frame(kwic(Programs, pattern = "communica*"))
s4 <- data.frame(kwic(Programs, pattern = "creat*"))
s5 <- data.frame(kwic(Programs, pattern = "patience"))
s6 <- data.frame(kwic(Programs, pattern = "lead*"))
s7 <- data.frame(kwic(Programs, pattern = "solve"))
s8 <- data.frame(kwic(Programs, pattern = "commit"))
s9 <- data.frame(kwic(Programs, pattern = "undertake"))
s10 <- data.frame(kwic(Programs, pattern = "manage*"))
s11 <- data.frame(kwic(Programs, pattern = "reflect"))
s12 <- data.frame(kwic(Programs, pattern = "control"))
s13 <- data.frame(kwic(Programs, pattern = "ethics"))
s14 <- data.frame(kwic(Programs, pattern = "tolerate"))
s15 <- data.frame(kwic(Programs, pattern = "argue"))
s16 <- data.frame(kwic(Programs, pattern = "conflict"))
s17 <- data.frame(kwic(Programs, pattern = "negocia*"))
s18 <- data.frame(kwic(Programs, pattern = "understand"))
s19 <- data.frame(kwic(Programs, pattern = "teamwork"))
s20 <- data.frame(kwic(Programs, pattern = "planning"))
s21 <- data.frame(kwic(Programs, pattern = "generate"))
s22 <- data.frame(kwic(Programs, pattern = "empathy"))
s23 <- data.frame(kwic(Programs, pattern = "share"))
s24 <- data.frame(kwic(Programs, pattern = "analyze"))
s25 <- data.frame(kwic(Programs, pattern = "acknowledge"))
s26 <- data.frame(kwic(Programs, pattern = "guide"))
s27 <- data.frame(kwic(Programs, pattern = "respect"))
s28 <- data.frame(kwic(Programs, pattern = "motivat*"))
s29 <- data.frame(kwic(Programs, pattern = "cooperat*"))
s30 <- data.frame(kwic(Programs, pattern = "strengthen"))
s31 <- data.frame(kwic(Programs, pattern = "thrust"))
s32 <- data.frame(kwic(Programs, pattern = phrase("bring closer")))
s33 <- data.frame(kwic(Programs, pattern = "bridge"))
s34 <- data.frame(kwic(Programs, pattern = "change"))
s35 <- data.frame(kwic(Programs, pattern = "appreciate"))
s36 <- data.frame(kwic(Programs, pattern = "foment"))
s37 <- data.frame(kwic(Programs, pattern = "interact"))
s38 <- data.frame(kwic(Programs, pattern = "identify"))
s39 <- data.frame(kwic(Programs, pattern = "compete"))
s40 <- data.frame(kwic(Programs, pattern = "manifest"))
s41 <- data.frame(kwic(Programs, pattern = "responsible"))
s42 <- data.frame(kwic(Programs, pattern = "evaluat*"))
s43 <- data.frame(kwic(Programs, pattern = "innovat*"))
s44 <- data.frame(kwic(Programs, pattern = "deci*"))
s45 <- data.frame(kwic(Programs, pattern = "flexibility"))
s46 <- data.frame(kwic(Programs, pattern = "persua*"))
s47 <- data.frame(kwic(Programs, pattern = "convinc*"))
s48 <- data.frame(kwic(Programs, pattern = "inspir*"))

df_list <- mget(paste0("s", 1:48))
SS <- do.call(rbind, df_list)
rm(list=setdiff(ls(), "SS"))
save.image("Results/Result2.RData")

